# https://cloud.google.com/appengine/docs/standard/python/config/appref

# application: facebook-atom
# version: 2
runtime: python27
threadsafe: true
api_version: 1
default_expiration: 1d

# background: https://github.com/snarfed/bridgy/issues/578
automatic_scaling:
  max_idle_instances: 1
  max_concurrent_requests: 12

builtins:
- remote_api: on

libraries:
- name: lxml
  version: latest
- name: ssl
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"
    Content-Security-Policy: "script-src https: localhost:8080 'unsafe-inline'; report-uri /csp-report;"
    Strict-Transport-Security: "max-age=16070400; includeSubDomains; preload"
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "SAMEORIGIN"
    X-XSS-Protection: "1; mode=block"

- url: /cookie
  script: cookie.application
  secure: always

skip_files:
- ^(.*/)?.*\.(c|cc|cpp|h|o|py[co]|so)$
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?(debian|docs?|examples?|l|pydocs?|python3|ref|samples?|tests?)/.*
- ^local/lib/python2.7/site-packages/setuptools/script\ \(dev\)\.tmpl$
